spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: Rinko@21
#      url: jdbc:mysql://localhost:3306/rinko?serverTimezone=Asia/Shanghai
#      initial-size: 5
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      filters: stat,wall
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      use-global-data-source-stat: true
#      stat-view-servlet:
#        login-password: admin
#        login-username: admin
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
server:
  port: 7895